[2024-03-05T21:03:58.214-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [queued]>
[2024-03-05T21:03:58.221-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [queued]>
[2024-03-05T21:03:58.221-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-05T21:03:58.237-0300] {taskinstance.py:2214} INFO - Executing <Task(DatabricksRunNowOperator): Extraindo-conversoes> on 2024-03-03 09:00:00+00:00
[2024-03-05T21:03:58.240-0300] {standard_task_runner.py:60} INFO - Started process 28699 to run task
[2024-03-05T21:03:58.246-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Executando-notebook-etl', 'Extraindo-conversoes', 'scheduled__2024-03-03T09:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmp3pnpo_lz']
[2024-03-05T21:03:58.247-0300] {standard_task_runner.py:88} INFO - Job 7: Subtask Extraindo-conversoes
[2024-03-05T21:03:58.287-0300] {task_command.py:423} INFO - Running <TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [running]> on host GabGalani.
[2024-03-05T21:03:58.323-0300] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'Extraindo-conversoes', field 'json'. Template: {'job_id': '292067935571330', 'notebook_params': {'data_execucao': '{{data_interval_end.strftime("%Y-%m-%d)}}'}}
Traceback (most recent call last):
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 186, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 186, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 186, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 186, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 173, in render_template
    template = jinja_env.from_string(value)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '"' at 29
[2024-03-05T21:03:58.324-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2357, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2907, in render_templates
    original_task.render_template_fields(context)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 186, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 186, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 186, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 186, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 173, in render_template
    template = jinja_env.from_string(value)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/gabriel/Documents/Airflow/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '"' at 29
[2024-03-05T21:03:58.328-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Executando-notebook-etl, task_id=Extraindo-conversoes, execution_date=20240303T090000, start_date=20240306T000358, end_date=20240306T000358
[2024-03-05T21:03:58.341-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task Extraindo-conversoes (unexpected char '"' at 29; 28699)
[2024-03-05T21:03:58.377-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T21:03:58.385-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T21:08:22.318-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [queued]>
[2024-03-05T21:08:22.325-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [queued]>
[2024-03-05T21:08:22.325-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-05T21:08:22.341-0300] {taskinstance.py:2214} INFO - Executing <Task(DatabricksRunNowOperator): Extraindo-conversoes> on 2024-03-03 09:00:00+00:00
[2024-03-05T21:08:22.343-0300] {standard_task_runner.py:60} INFO - Started process 31204 to run task
[2024-03-05T21:08:22.347-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Executando-notebook-etl', 'Extraindo-conversoes', 'scheduled__2024-03-03T09:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmpwwzgp1tj']
[2024-03-05T21:08:22.348-0300] {standard_task_runner.py:88} INFO - Job 7: Subtask Extraindo-conversoes
[2024-03-05T21:08:22.378-0300] {task_command.py:423} INFO - Running <TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [running]> on host GabGalani.
[2024-03-05T21:08:22.435-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Executando-notebook-etl' AIRFLOW_CTX_TASK_ID='Extraindo-conversoes' AIRFLOW_CTX_EXECUTION_DATE='2024-03-03T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-03T09:00:00+00:00'
[2024-03-05T21:08:22.439-0300] {base.py:83} INFO - Using connection ID 'databricks_default' for task execution.
[2024-03-05T21:08:22.451-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T21:08:22.804-0300] {databricks.py:54} INFO - Run submitted with run_id: 52011235895470
[2024-03-05T21:08:22.804-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T21:08:22.981-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T21:08:23.149-0300] {databricks.py:108} INFO - Extraindo-conversoes in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2024-03-05T21:08:23.150-0300] {databricks.py:109} INFO - View run status, Spark UI, and logs at https://adb-2816171104137333.13.azuredatabricks.net/?o=2816171104137333#job/292067935571330/run/52011235895470
[2024-03-05T21:08:23.150-0300] {databricks.py:110} INFO - Sleeping for 30 seconds.
[2024-03-05T21:08:53.181-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T21:08:53.537-0300] {databricks.py:65} INFO - Extraindo-conversoes completed successfully.
[2024-03-05T21:08:53.538-0300] {databricks.py:66} INFO - View run status, Spark UI, and logs at https://adb-2816171104137333.13.azuredatabricks.net/?o=2816171104137333#job/292067935571330/run/52011235895470
[2024-03-05T21:08:53.545-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Executando-notebook-etl, task_id=Extraindo-conversoes, execution_date=20240303T090000, start_date=20240306T000822, end_date=20240306T000853
[2024-03-05T21:08:53.581-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-05T21:08:53.593-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T21:39:44.523-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [queued]>
[2024-03-05T21:39:44.530-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [queued]>
[2024-03-05T21:39:44.531-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-05T21:39:44.547-0300] {taskinstance.py:2214} INFO - Executing <Task(DatabricksRunNowOperator): Extraindo-conversoes> on 2024-03-03 09:00:00+00:00
[2024-03-05T21:39:44.549-0300] {standard_task_runner.py:60} INFO - Started process 52217 to run task
[2024-03-05T21:39:44.551-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Executando-notebook-etl', 'Extraindo-conversoes', 'scheduled__2024-03-03T09:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_dag.py', '--cfg-path', '/tmp/tmprnjz9zgi']
[2024-03-05T21:39:44.552-0300] {standard_task_runner.py:88} INFO - Job 48: Subtask Extraindo-conversoes
[2024-03-05T21:39:44.581-0300] {task_command.py:423} INFO - Running <TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2024-03-03T09:00:00+00:00 [running]> on host GabGalani.
[2024-03-05T21:39:44.641-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Executando-notebook-etl' AIRFLOW_CTX_TASK_ID='Extraindo-conversoes' AIRFLOW_CTX_EXECUTION_DATE='2024-03-03T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-03T09:00:00+00:00'
[2024-03-05T21:39:44.646-0300] {base.py:83} INFO - Using connection ID 'databricks_default' for task execution.
[2024-03-05T21:39:44.659-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T21:39:45.054-0300] {databricks.py:54} INFO - Run submitted with run_id: 1124911173346216
[2024-03-05T21:39:45.055-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T21:39:45.227-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T21:39:45.432-0300] {databricks.py:108} INFO - Extraindo-conversoes in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2024-03-05T21:39:45.433-0300] {databricks.py:109} INFO - View run status, Spark UI, and logs at https://adb-2816171104137333.13.azuredatabricks.net/?o=2816171104137333#job/292067935571330/run/1124911173346216
[2024-03-05T21:39:45.433-0300] {databricks.py:110} INFO - Sleeping for 30 seconds.
[2024-03-05T21:40:15.455-0300] {databricks_base.py:500} INFO - Using token auth.
[2024-03-05T21:40:15.737-0300] {databricks.py:65} INFO - Extraindo-conversoes completed successfully.
[2024-03-05T21:40:15.738-0300] {databricks.py:66} INFO - View run status, Spark UI, and logs at https://adb-2816171104137333.13.azuredatabricks.net/?o=2816171104137333#job/292067935571330/run/1124911173346216
[2024-03-05T21:40:15.743-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Executando-notebook-etl, task_id=Extraindo-conversoes, execution_date=20240303T090000, start_date=20240306T003944, end_date=20240306T004015
[2024-03-05T21:40:15.780-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-05T21:40:15.795-0300] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
